# Generated by Django 2.2.6 on 2019-11-03 01:11

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion

from audit_log.db.migrations.operations import CreateAuditLogModel


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLoggingContext',
            fields=[
                ('context_type', models.CharField(choices=[('HTTP request', 'http-request'), ('Management command', 'management-command'), ('Celery task', 'celery-task'), ('Test', 'test')], max_length=128, primary_key=True, serialize=False)),
                ('context', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLoggedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('some_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NonAuditLoggedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('some_text', models.TextField()),
            ],
        ),
        CreateAuditLogModel(
            name='AuditLoggedModelAuditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_type', models.CharField(choices=[('HTTP request', 'http-request'), ('Management command', 'management-command'), ('Celery task', 'celery-task'), ('Test', 'test')], max_length=128)),
                ('context', django.contrib.postgres.fields.jsonb.JSONField()),
                ('action', models.CharField(choices=[('Insert', 'INSERT'), ('Update', 'UPDATE'), ('Delete', 'DELETE')], max_length=6)),
                ('at', models.DateTimeField()),
                ('changes', django.contrib.postgres.fields.jsonb.JSONField()),
                ('audit_logged_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='tests.AuditLoggedModel')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            audit_log_for='tests.AuditLoggedModel',
        ),
    ]
