# Generated by Django 3.1.4 on 2020-12-06 02:39

import audit_log.fields
from django.db import migrations, models
from audit_log.db.migrations.operations import RemoveAuditLogging


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myconvertedtoauditloggedmodel',
            name='audit_logs',
            field=audit_log.fields.AuditLogsField(to='tests.auditlogentry'),
        ),
        migrations.CreateModel(
            name='MyNoLongerAuditLoggedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('some_text', models.TextField()),
                ('audit_logs', audit_log.fields.AuditLogsField(to='tests.auditlogentry')),
            ],
            options={
                'abstract': False,
            },
        ),
	RemoveAuditLogging(model='MyNoLongerManuallyAuditLoggedModel'),
    ]
