# Generated by Django 3.1.4 on 2020-12-06 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_auto_20201206_0239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mynolongerauditloggedmodel',
            name='audit_logs',
        ),
    ]
